// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvciyI_yzJJAR6hRSBS5EIczGJkcMFfD4',
    appId: '1:699607251739:web:34bce3c3da3107b6dff1be',
    messagingSenderId: '699607251739',
    projectId: 'todoappflutter01',
    authDomain: 'todoappflutter01.firebaseapp.com',
    databaseURL: 'https://todoappflutter01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todoappflutter01.firebasestorage.app',
    measurementId: 'G-D3C4DR12M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLXgI_2N92F1nRMdYgJft4X_ANB1z1Tt8',
    appId: '1:699607251739:android:7b3c2b6de89982d9dff1be',
    messagingSenderId: '699607251739',
    projectId: 'todoappflutter01',
    databaseURL: 'https://todoappflutter01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todoappflutter01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvU79kyQcpqiqCyVRtbmSvO9z00WvVRQA',
    appId: '1:699607251739:ios:592119a415f5b638dff1be',
    messagingSenderId: '699607251739',
    projectId: 'todoappflutter01',
    databaseURL: 'https://todoappflutter01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todoappflutter01.firebasestorage.app',
    iosBundleId: 'com.example.taskflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvU79kyQcpqiqCyVRtbmSvO9z00WvVRQA',
    appId: '1:699607251739:ios:592119a415f5b638dff1be',
    messagingSenderId: '699607251739',
    projectId: 'todoappflutter01',
    databaseURL: 'https://todoappflutter01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todoappflutter01.firebasestorage.app',
    iosBundleId: 'com.example.taskflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvciyI_yzJJAR6hRSBS5EIczGJkcMFfD4',
    appId: '1:699607251739:web:44028740aec2356adff1be',
    messagingSenderId: '699607251739',
    projectId: 'todoappflutter01',
    authDomain: 'todoappflutter01.firebaseapp.com',
    databaseURL: 'https://todoappflutter01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todoappflutter01.firebasestorage.app',
    measurementId: 'G-RCF9VPYGV3',
  );

}